/**
 * Export Metadata — Versi tarif, timestamp, dan disclaimer untuk file ekspor
 * Ditambahkan ke header/footer file CSV dan XML.
 *
 * Validates: Fitur Transparansi #2 (disclaimer di file ekspor)
 * Validates: Fitur Transparansi #4 (metadata versi tarif + timestamp)
 */

import { LEGAL_DISCLAIMER_SHORT } from '@/components/layout/Footer';

/** Versi tarif TER yang digunakan */
export const TER_VERSION = 'PP 58/2023 jo. PMK 168/2023';

/** Versi aplikasi */
export const APP_VERSION = '0.1.0';

/**
 * Generate metadata header untuk file ekspor.
 * Berisi: versi aplikasi, versi tarif, timestamp generate, disclaimer.
 */
export interface ExportMetadata {
  app_version: string;
  ter_version: string;
  generated_at: string;
  generated_by: string;
  period: string;
  disclaimer: string;
}

/**
 * Buat metadata ekspor dengan timestamp saat ini.
 */
export function createExportMetadata(
  periodMonth: number,
  periodYear: number,
  companyName: string,
): ExportMetadata {
  const now = new Date();
  const monthStr = String(periodMonth).padStart(2, '0');

  return {
    app_version: `Tax-Ready Payroll v${APP_VERSION}`,
    ter_version: TER_VERSION,
    generated_at: now.toISOString(),
    generated_by: companyName,
    period: `${periodYear}-${monthStr}`,
    disclaimer: LEGAL_DISCLAIMER_SHORT,
  };
}

/**
 * Format metadata sebagai baris komentar CSV (prefix #).
 */
export function formatMetadataAsCSVComments(metadata: ExportMetadata): string {
  const lines = [
    `# Generated by: ${metadata.app_version}`,
    `# Tarif version: ${metadata.ter_version}`,
    `# Generated at: ${metadata.generated_at}`,
    `# Company: ${metadata.generated_by}`,
    `# Period: ${metadata.period}`,
    `# Disclaimer: ${metadata.disclaimer}`,
    '#',
  ];
  return lines.join('\n');
}

/**
 * Format metadata sebagai elemen XML <metadata>.
 */
export function formatMetadataAsXML(metadata: ExportMetadata): string {
  const lines = [
    '  <metadata>',
    `    <app_version>${escapeXMLValue(metadata.app_version)}</app_version>`,
    `    <ter_version>${escapeXMLValue(metadata.ter_version)}</ter_version>`,
    `    <generated_at>${metadata.generated_at}</generated_at>`,
    `    <generated_by>${escapeXMLValue(metadata.generated_by)}</generated_by>`,
    `    <period>${metadata.period}</period>`,
    `    <disclaimer>${escapeXMLValue(metadata.disclaimer)}</disclaimer>`,
    '  </metadata>',
  ];
  return lines.join('\n');
}

function escapeXMLValue(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}
